### ISSUE TITLE
Ordering of custom locations is not kept

### ISSUE THREAD

**Issue by tom-kuca** [HanXHX/ansible-nginx#24]
Given a configuration file

```yaml
nginx_vhosts:
  - name:
    - example.com
    location:
      '= /': 
        - '[ configuration A ]' 
      '/': 
        - '[ configuration B ]'
      '/documents/':
        - '[ configuration C ]'
      '^~ /images/':
        - '[ configuration D ]'
      '~* \.(gif|jpg|jpeg)$': 
        - '[ configuration E ]'
```
the result is unpredicatable. it can be i.e.

```nginx
location ^~ /images/ {
    [ configuration D ]
}
location / {
    [ configuration B ]
}
location /documents/ {
    [ configuration C ]
}
location ~* \.(gif|jpg|jpeg)$ {
    [ configuration E ]
}
location = / {
    [ configuration A ]
}
```
Locations are stored in a dictionary which doesn't keep ordering. The ordering is important, because regular expressions are searched from top to bottom:

Fom [nginx doc](http://nginx.org/en/docs/http/ngx_http_core_module.html#location):
> Then regular expressions are checked, in the order of their appearance in the configuration file. The search of regular expressions terminates on the first match, and the corresponding configuration is used. 

I tried to find a way how to solve it without changing the syntax, but it seems it's not possible. see
http://stackoverflow.com/questions/28414055/how-to-enforce-the-order-of-with-dict-in-ansible

**Comment by HanXHX** [comment]
Hi @tom-kuca 

I will think about a solution tomorrow  or this week-end (hashlist with backward compatibility ?).

**Comment by tom-kuca** [comment]
Hi, thanks for the fast response. I was also thinking about alternatives, hashlist is quite verbose.

``` yaml
location:
  - key: '= /': 
    value: 
      - '[ configuration A ]' 
```

I prefer less verbose:

``` yaml
location:
   - location = / {
       [ configuration A ]
     }
```

It's also closer to `nginx.conf` syntax, it's easier to transform the rules. Thinking whether there are some downsides or not.
